name: Trigger-All-Workflows  # 主要工作流的名称

on:
  workflow_dispatch:  # 手动触发：通过 GitHub UI 来触发
  schedule:
    - cron: 0 20 * * 5  # 北京时间星期六凌晨4点，定时触发

jobs:

    IPQ60XX-LibWrt:
      uses: ./.github/workflows/IPQ60XX-LibWrt.yml

    IPQ60XX-VIKINGYFY:
      uses: ./.github/workflows/IPQ60XX-VIKINGYFY.yml

    IPQ60XX-qosmio:
      uses: ./.github/workflows/IPQ60XX-qosmio.yml

    All-Clean:
      uses: ./.github/workflows/All-Clean.yml
